name: context info

on: push

jobs:
  describe-run:
    runs-on: ubuntu-latest
    steps:
      - name: Print run contexts
        shell: bash
        run: |
          echo "Repository:  ${{ github.repository }}"
          echo "Branch:      ${{ github.ref_name }}"
          echo "Commit SHA:  ${{ github.sha }}"
          echo "Event:       ${{ github.event_name }}"
          echo "Runner OS:   ${{ runner.os }}"
