name: run label

on: push

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Print build label
        shell: bash
        run: echo "${{ format('build-{0}-{1}', github.run_number, github.ref_name) }}"
